version: '2'
services:
  mysql:
    image: "mysql:5.6"
    restart: always
    environment:
     - MYSQL_ROOT_PASSWORD=123456
     - MYSQL_DATABASE=contact-center
     - MYSQL_USER=admin
     - MYSQL_PASSWORD=admin123456
    ports:
     - "3306:3306"
    volumes:
     - $PWD/mysql/data:/var/lib/mysql
     - $PWD/mysql/config:/etc/mysql

  redis:
    image: redis:latest
    restart: always
    command: redis-server --appendonly yes
    volumes:
     - $PWD/redis/data:/data
    ports:
     - "6379:6379"

  contact-center:
    image: "chatopera/contact-center:develop"
    restart: always
    ports:
      - "8035:8080"
      - "8036:8036"
    volumes:
     - $PWD/contact-center/data:/data
     - $PWD/contact-center/logs:/logs
    environment:
     - JAVA_OPTS=-Xmx12288m -Xms2048m -XX:PermSize=256m -XX:MaxPermSize=1024m -Djava.net.preferIPv4Stack=true
     - SERVER_PORT=8035
     - SERVER_LOG_PATH=/logs
     - SERVER_LOG_LEVEL=INFO
     - WEB_UPLOAD_PATH=/data
     - SPRING_FREEMARKER_CACHE=true
     - SPRING_DATA_ELASTICSEARCH_PROPERTIES_PATH_DATA=/data
     - UK_IM_SERVER_PORT=8036
     - UK_IM_SERVER_HOST=localhost
     - UK_IM_SERVER_THREADS=10
     - SPRING_DATASOURCE_TYPE=com.alibaba.druid.pool.DruidDataSource
     - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.jdbc.Driver
     - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/contact-center?useUnicode=true&characterEncoding=UTF-8
     - SPRING_DATASOURCE_USERNAME=root
     - SPRING_DATASOURCE_PASSWORD=123456
     - MANAGEMENT_SECURITY_ENABLED=false
     - SPRING_REDIS_DATABASE=2
     - SPRING_REDIS_HOST=redis
     - SPRING_REDIS_PORT=6379
     - CSKEFU_CALLOUT_WATCH_INTERVAL=60000
    depends_on:
     - mysql
     - redis